version: '3.7'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./foodgram/.env

  web: 
    build: . 
    restart: always 
    command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000 
    depends_on: 
      - db 
    env_file: 
      - ./foodgram/.env 
    volumes: 
      - static_volume:/code/static/ 
      - media_volume:/code/media/ 
    expose: 
      - 8000 
  
  nginx: 
    build: ./nginx 
    depends_on: 
      - web 
    ports: 
      - 80:80 
    volumes: 
      - static_volume:/code/static/ 
      - media_volume:/code/media/ 